### ISSUE TITLE
Connection lines are drawn inconsistently

### ISSUE THREAD

**Issue by richcorbs** [musclesoft/jquery-connections#1]
I create boxes and connect them and the connection lines are drawn just fine. When I refresh the page the lines come back differently and I can't predict how/why/when they are different. Are the "rules" for drawing lines documented anywhere besides in the code? Can I do anything about this?

For instance, when I move a box (and save its new location) and update the lines they display one way. Then I refresh the page and the lines change. The boxes don't move at all but the connection line changes. Like going between the same two boxes in different paths:

```
   +--------- 1
   |
   |
   2
```

or

```
             1
             |
             |
   2 --------+
```

Any help is appreciated.

**Comment by richcorbs** [comment]
Another data point: It might happen only when a box has multiple connections. Does that help at all?

**Comment by diamond-msc** [comment]
The rules are documented in the wiki:

https://github.com/musclesoft/jquery-connections/wiki/Line-Drawing-Strategies

So, with `from:'#one', to: '#two'` the result should always be as in your 2nd example.

Maybe after moving your elements, saving and reloading, the DOM order of your elements has changed.
If you somehow select by DOM order (e. g. `from:'#id :nth-child(1)', to: '#id :nth-child(2)'`) the connections may appear 'random', e. g. if `#one` appears as the 2nd child in the DOM..

Could you give an example on how your selectors look like?
Two fiddles demonstrating the different outcomes would be perfect.

**Comment by richcorbs** [comment]
I read that page previously but now I _understand_ it. Thank you. "Down and over" is perfectly consistent.
