### ISSUE TITLE
How to obtain id from en to from connection line

### ISSUE THREAD

**Issue by mchendriks** [musclesoft/jquery-connections#10]
After a connection has been made between two draggabke divs i would like to get the ids from the from and the to draggabke divs after clicking on the connection line. 
Is this possible? 
Any directions how to obtain are appreciated.

**Comment by diamond-msc** [comment]
Using public API you could pass the respective IDs to the `class` option, when creating a connection.
Your click handler can then look at the classnames of the clicked element, and find the matching elements by ID.

Using non-public API you can identify the two nodes by looking at the connection element `data`. See http://jsfiddle.net/FP7Zy/240/ for an example.
