### ISSUE TITLE
mouseover events for overlapped connections

### ISSUE THREAD

**Issue by rajasekharballa** [musclesoft/jquery-connections#12]
![screenshot from 2018-05-09 11-56-36 copy png](https://user-images.githubusercontent.com/3645967/39799311-7146b66e-5381-11e8-9cf3-35b9a8bcb3f0.png)

Trying to get the mouseover event on connections. since the connection divs are overlapped, not able to get the mouseover event of overlapped connections (part of 2 and 3 in picture) 

Is there a way to capture the mouseover events of connecting lines accurately ..?

**Comment by diamond-msc** [comment]
Sorry for being extremely late.

I'm afraid this is not possible.

CSS based solutions seem to have no browser support (e.g. `clip-path`) 😿 

So, for the case outlined in the screenshot we would need to make jquery-connections aware of the final shape of the connection and add dedicated support, e.g. by using multiple elements or SVG.

Unfortunately this is out of scope for the project.
