### ISSUE TITLE
Styling the ends of a connector

### ISSUE THREAD

**Issue by yannnic** [musclesoft/jquery-connections#17]
Hi,
is it possible to style each end of a connector ? By example a different color, or shape.
Thanks and congrats for this simple and useful lib.
Yann

**Comment by diamond-msc** [comment]
@yannnic 

You can target individual edges of a connection (top, left, bottom, right) using the `borderClasses` option. However, the styling options are fairly limited. (Some CSS border properties only, e.g. `border-top-color`.)

In addition to that, with `borderClasses` set, you can create additional elements by using CSS `::before` and `::after`. Again, the possibilities are limited, but may yield acceptable results with proper styling. See http://jsfiddle.net/dcfo5qxj/ for an example.

**Comment by yannnic** [comment]
Hi, it is more than what i was hoping for ! Thanks a lot !!

**Comment by yannnic** [comment]
hmm.. I would love to get a pseudo element at each end of a connection. Naively, i tried to create a second pseudo element with ::before, but to no avail...

**Comment by yannnic** [comment]
NB : to have a pseudo element at each end is actually a trick to avoid another pb : your previous solution works fine... until i move around one of the connected elements... Logicially, as i move one of them around the other one (above, below, to the right, to the left), the pseudo element migrates from one end to the other. And it is not what i want... Then, i tried to add a pseudo element at each end... That's it :)

**Comment by yannnic** [comment]
> hmm.. I would love to get a pseudo element at each end of a connection. Naively, i tried to create a second pseudo element with ::before, but to no avail...

ok, it works : i had forgotten to define : connection::before in the CSS, sorry
