### ISSUE TITLE
Any way to force side connections

### ISSUE THREAD

**Issue by mrichardsdev** [musclesoft/jquery-connections#18]
Is there any way to force the lines to connect to the left and right sides only?

![image](https://user-images.githubusercontent.com/33011308/62110968-e9737b00-b2f2-11e9-9193-35d7fa8a4be7.png)

I would like to be able to link specific line items "tr" 's of different tables but can not have the lines go over other line items, so need to force the lines to go to the sides only so you can tell which items belong together.

**Comment by diamond-msc** [comment]
Sorry for not responding for so long.

The orientation of the connection can be controlled by the order of `from` and `to` options.
See https://github.com/musclesoft/jquery-connections/issues/1#issuecomment-25328061 for more explanation.

**Comment by diamond-msc** [comment]
I reread your question. What you want is not directly possible. You have to establish an invisible "anchor" element at the position of the center of the vertical line.
See https://github.com/musclesoft/jquery-connections/issues/9#issuecomment-216064966.

As this was now requested two times, maybe we could find a way to implement it. I'm open for ideas and contributions. Maybe we should start with how the API would look like.

**Comment by mrichardsdev** [comment]
I ended up coming up with my own solution using svg's (happy to supply code if you want to have a look)

![image](https://user-images.githubusercontent.com/33011308/75321608-3c330680-58c5-11ea-8682-32b8b60eafa1.png) 
![image](https://user-images.githubusercontent.com/33011308/75321807-aba8f600-58c5-11ea-9c24-3e6f72a55e84.png)


The way i did it is just created a large svg to cover my 'work area' and set the z-index lower than the items, then use jquery to determine the edges of the source and target, then do some maths to work out which direction it should go and whether it has to double back on itself

It could just as easily be done using an svg for each join, and placing them programmatically, simmiler to how you currently do it.

**Comment by diamond-msc** [comment]
I see. Nice idea. As the two approaches are very different, for this project I'd like to stick to the cheap single-DOM-element approach.
