### ISSUE TITLE
Drawing Strategies line

### ISSUE THREAD

**Issue by crestin** [musclesoft/jquery-connections#2]
![line](https://f.cloud.github.com/assets/5337065/2266445/6a06a360-9e99-11e3-96c0-3cb2a1a023a3.jpg)

how to draw i want, thanks!

**Comment by diamond-msc** [comment]
Although not directly supported, drawing thin lines like in your example can already be done.
See this example: http://jsfiddle.net/b0rw5on2/ (based on http://stackoverflow.com/a/19848543)
