### ISSUE TITLE
Anchors not always connected

### ISSUE THREAD

**Issue by GithubRa** [musclesoft/jquery-connections#21]
Hi, sometimes the lines are not correctly connected to the anchor.

to make this happen i used two anchors, you can see this in the images below.

![lineProblem](https://user-images.githubusercontent.com/38880120/89898164-847a8280-dbe0-11ea-8c35-835630d1fb97.png)
![lineProblem1](https://user-images.githubusercontent.com/38880120/89898166-85131900-dbe0-11ea-83aa-27265158df09.png)

The anchors and line are build like this :
```
.connected {
	height: 0px;
	width: 0px;
	position: absolute;
	border: none;
	background: rgba(0, 111, 186, 1);
}

connection {
	border: 10px solid rgba(0, 111, 186, 1);
	border-radius: 30px;
	pointer-events: none;
	box-sizing: content-box;
	z-index: 9;
}
```

When i scroll sometimes it fits perfect, other times you see an small space in between the lines.

is there a way to fix this?

**Comment by diamond-msc** [comment]
This is a tricky one. The gaps are created when the elements have a fractional pixel size and/or position.
I haven't found a good solution yet. In some cases making the elements and connections a bit bigger may help cover the gaps. This workaround might lead to other issues though.

For example:

```css
.connected, connection {
  transform: scale(1.02);
}
```
