### ISSUE TITLE
Is there any option to make the lines straight.

### ISSUE THREAD

**Issue by gyanasaireddy** [musclesoft/jquery-connections#22]
Instead of being bent at a particular point.
Is there a way of the line being straight 
( |__ -> \ )

**Comment by diamond-msc** [comment]
Hey @gyanasaireddy. Please have a look at #2 for a solution/workaround.

**Comment by gyanasaireddy** [comment]
Thank you for your reply. I will check the fiddle given now.

**Comment by gyanasaireddy** [comment]
Thank you very much !!. It worked

**Comment by gyanasaireddy** [comment]
Is there a way to add an event listener to the straight line that is generated from the fiddle[https://github.com/musclesoft/jquery-connections/issues/2]()

AT present the event listener is being added to the entire invisible box. Can I confine It to only the straight line.?
