### ISSUE TITLE
How to change the start side and the end side of the connection between two elements? 

### ISSUE THREAD

**Issue by gatre96** [musclesoft/jquery-connections#32]
I'm actually working on a binary tree and i need to connect nodes. The code works good for me, but i would like to change the starting point of the connection. When i connect a partent node to child nodes, the connections starts from bottom of parent node, but i want it to start from left and the connect to top border of the child(for left child, right for the right child)

**Comment by dcsaszar** [comment]
Would switching `from` and `to` do the trick?
See https://github.com/musclesoft/jquery-connections/wiki/Line-Drawing-Strategies for why I think this could work.

**Comment by gatre96** [comment]
Sorry for the late answer, anyway i read the line drawing strategies and this helped. I didn't actually try tour solution because i switched to another way to do what i had to do, but reading the drawing strategies it should work like i wanted.
